platform: linux

image_resource:
  type: docker-image
  source:
    repository: hashicorp/terraform
    tag: "0.11.8"

inputs:
- name: source

outputs:
- name: terraform

caches:
- path: terraform-cache

params:
  command:
  directories:
  cache: "false"
  lock_timeout: 5m
  access_key:
  secret_key:
  session_token:
  github_token: ((github-token))

run:
  path: source/concourse/tasks/terraform/terraform.sh
